# Generated by Django 3.0.8 on 2020-07-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParamikoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
            ],
        ),
    ]
