# Generated by Django 3.0.8 on 2020-07-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_paramikomodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramikomodel',
            name='user',
        ),
    ]
